"""empty message

Revision ID: b8bbcf8c84fe
Revises: 
Create Date: 2017-10-02 01:20:23.294314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8bbcf8c84fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'company')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('company', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
